// The sample reading seeded by the "first day" button — a condensed,
// editor-authored study summary of Hawkins v. McGee and its companion
// material (public-domain 1929 opinion, summarized in our own words; see
// docs/student-hub/student-hub-design.md). Real sessions use the text of
// the student's own scanned casebook instead.

export const SAMPLE_TITLE = 'Hawkins v. McGee';
export const SAMPLE_CITATION = '84 N.H. 114, 146 A. 641 (1929)';
export const SAMPLE_SOURCE_LABEL = 'sample reading — the "hairy hand" case';

export const SAMPLE_READING = `HAWKINS v. McGEE, Supreme Court of New Hampshire, 1929. 84 N.H. 114, 146 A. 641.
Assumpsit against a surgeon for breach of an alleged warranty of the success of an operation (removal of scar tissue from plaintiff's burned right palm and grafting of skin from his chest). Jury verdict of $3,000 for plaintiff on the warranty count; a negligence count was nonsuited. Trial court ordered the verdict set aside as excessive unless plaintiff remitted all above $500; plaintiff refused.
BRANCH, J.: Statements that the boy would be in the hospital "three or four days, not over four," and back to work "a few days" later, were mere opinions or predictions and impose no contractual liability. But the statement "I will guarantee to make the hand a hundred per cent perfect hand or a hundred per cent good hand," if uttered, would establish a warranty. Whether words could possibly bear the contractual meaning imputed to them is a preliminary question of law, but the trial court did not err in submitting the contract question to the jury: there was evidence the defendant repeatedly solicited the operation, and plaintiff's counsel advanced the theory that he wished to "experiment on skin grafting," in which he had little experience — supporting the inference that the words were intended at face value as an inducement to consent.
Damages: the jury charge allowed recovery for (1) pain and suffering from the operation and (2) ill effects of the operation on the hand. This was error. Contract damages are "compensation for a breach, measured in the terms of the contract"; the purpose is "to put the plaintiff in as good a position as he would have been in had the defendant kept his contract" (Williston). The case is analogous to a machine warranted to do certain work: damages are the difference between the value of the machine as warranted and its actual value, plus incidental losses within the parties' contemplation. The true measure here is the difference between the value to him of a perfect or good hand, as promised, and the value of his hand in its present condition, plus incidental consequences fairly within the contemplation of the parties. Pain incident to the operation was part of the consideration the plaintiff gave — part of the price paid for a good hand — and furnishes no test of the difference in value. Worsening of the hand is not a separate element; it is subsumed in the true rule, and damages could be assessed for failure to improve the hand even absent worsening. Defendant's requested instructions (including that both parties must have "understood" a guarantee) were properly denied: the standard is external, not internal; mental reservations are immaterial where the promise was made and relied on. New trial.
NOTE: On the eve of the new trial McGee paid Hawkins $1,400 and settled. McGee's suit against his liability insurer failed: the policy covered "malpractice, error, or mistake," not the "special contract." McGee v. United States Fidelity & Guaranty Co., 53 F.2d 953 (1st Cir. 1931). The complaint had alleged three months' hospitalization and that the grafted tissue became matted and hair-growing, leaving the hand practically useless where before it had been practical and useful.
SULLIVAN v. O'CONNOR, 363 Mass. 579, 296 N.E.2d 183 (1973): surgeon promised to enhance a professional entertainer's appearance by nose surgery; three operations left it worse. Jury instructions embraced a reliance measure — out-of-pocket expenses plus worsening of condition plus pain and suffering of the unnecessary third operation — and the court upheld them, doubting whether the expectancy (value of the promised nose) should be available in such cases, while noting plaintiff waived any claim to it.
CONTEXT (Fuller & Perdue, The Reliance Interest in Contract Damages): three protectable interests — restitution (disgorge value conferred on defendant), reliance (restore plaintiff's position before the promise), expectation (give plaintiff the value of the promised performance). Restitution presents the strongest claim to judicial intervention (defendant gained what plaintiff lost); expectation, though the default measure, arguably presents the least impressive claim.`;
